 version: '3'
 services:
   web:
     command: python docker_bot.py
     environment:
       - PYTHONUNBUFFERED=0
     build:
       context: .
       dockerfile: ./Dockerfile
     depends_on:
       - selenium
   selenium:
       image: selenium/standalone-chrome
       shm_size: 128M
